### ISSUE TITLE
[ULCC-6] Add flow and eslint to project

### ISSUE THREAD

**Issue by Fedkasin** [Fedkasin/lot-management-client#6]
Add propTypes to each component and add eslint to dependencies.

**Refference:**
https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by andrewjohnsson** [comment]
@Fedkasin @k1r1k1 
I suggest to use airbnb config as base for our eslint config:
https://www.npmjs.com/package/eslint-config-airbnb
