### ISSUE TITLE
[LMC-18] - Add refresh for agent watches

### ISSUE THREAD

**Issue by andrewjohnsson** [Fedkasin/lot-management-client#75]
https://github.com/andrewjohnsson/lot-management-api/issues/37 issue couldn't be addressed at client level even after the DB was fixed automatically/manually by content operator

This highlights a feature we currently miss at the client - agent watch list must support pull-to-refresh. We need to implement this in agent watch lots screen as well

**Acceptance Criteria**
- [x] pull-to-refresh is added to agent watch jobs listing component
- [x] pull-to-refresh is added to agent watch job lot listings component

**Comment by k1r1k1** [comment]
@andrewjohnsson "Pull to refresh" feature is actually realized at "agent watch list", but there`s some issue with it. Thanks for reporting!
