### ISSUE TITLE
[LMC-19] - automatic toggle the agent edit mode off

### ISSUE THREAD

**Issue by andrewjohnsson** [Fedkasin/lot-management-client#76]
After enabling, edit mode is not being auto-disabled after performing any action such as adding new job. Please make it disable itself in such scenarios

**Comment by k1r1k1** [comment]
@andrewjohnsson Resolved with this [commit](https://github.com/Fedkasin/lot-management-client/commit/5732f493a44e586a007d611b43acc14156abef47)
